### ISSUE TITLE
新規登録(お店サイド)

### ISSUE THREAD

**Issue by junichi-fukushima** [fukushima-group/one_plate#21]
メールアドレスによる新規登録を実装する
１、メールアドレス、電話番号、パスワード、パスワード確認用
代表者の名字、名前、名字（カナ）、名前（カナ）、店舗名、
オープン日、郵便番号、都道府県、市区町村、番地、建物名を
入力し、「確認画面へ」のボタンを押すと確認画面に遷移する
２、パラメータで送られた情報を、確認画面に表示する
３、確認画面上の「登録する」ボタンを押したら、サーバーサイド
にパラメータが送られデータが登録される。その後
トップページに遷移する。

**Comment by WAKUZO** [comment]
実装中

[ブランチ：フロント新規登録（お店サイド）](https://github.com/fukushima-group/one_plate/tree/%E3%83%A6%E3%83%BC%E3%82%B6%E3%83%BC%E6%96%B0%E8%A6%8F%E7%99%BB%E9%8C%B2%EF%BC%88%E3%83%93%E3%83%A5%E3%83%BC%EF%BC%89)
